// hive/angular/app/dashboard.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'welcome',
    template: '<div class="welcome">Welcome</div>',
    styles: [`
        .welcome {
            text-align: center;
            line-height: 5em;
            font-size: 3rem;
            
            color: blueviolet;
            text-shadow: 5px 5px 5px #344020;
        }
    `]
})
export class DashboardComponent {}

// hive/my-project/src/components/Dashboard.vue
<template>
    <div class="welcome">Welcome</div>
</template>

<script>
    export default {
        name: 'dashboard',
        template: `<div class="welcome">Welcome</div>`,
        data: () => ({}),
        render: h => h(this),
    };
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
    .welcome {
        text-align: center;
        line-height: 5em;
        font-size: 3rem;

        color: blueviolet;
        text-shadow: 5px 5px 5px #344020;
    }
</style>
